# Generated by Django 5.2.1 on 2025-07-04 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
    ]
